spring:
  application:
    name: paymentProcess

  data:
    mongodb:
      uri: "mongodb+srv://Manoj_Gopi:Fsgit%40321@cluster0.pgnyvuh.mongodb.net/DATACONTROL?retryWrites=true&w=majority&appName=Cluster0"

server:
  port: 5000


api:
  Ml:
    url: http://10.30.0.104:8000/findrules
  auth:
    header:
      #      Authorization:
#      Content-Type: application/json